project_id = "jckwavzrpyczdkbwxnqb"

[functions.send-invite]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.list-users]
verify_jwt = true

[functions.delete-user]
verify_jwt = true
